### ISSUE TITLE
Error at fetching version history

### ISSUE THREAD

**Issue by bmcilw1** [slamotte/vault2git#11]
After using the script a few weeks ago successfully, now for some reason i'm having the following error:

 INFO vault2git: Starting at Tue Feb 02 17:27:26 -0600 2016
 INFO vault2git: Prepare destination folder
 INFO vault2git: Set Vault working folder
 INFO vault2git: Fetch version history
./converter.rb:128:in `convert': undefined method `children' for nil:NilClass (NoMethodError)
        from vault2git.rb:7

My ruby: ruby 1.8.7 (2013-06-27 patchlevel 374) [i386-mingw32]

**Comment by slamotte** [comment]
Interesting. The error stems from this line:

`versions = vault_command('versionhistory') % :history`

which results in `versions` being assigned `nil`. Then on the next line (line 128) we get the error about "undefined method children for nil".

The question is, why is no history being returned? I recommend you run the `versionhistory` Vault command from a command line and let me know what is returned for your repo. Thanks!

**Comment by bmcilw1** [comment]
I found the issue, in the log the username param was blank, so when I ran the vault command as in the log I got an auth error, but upon suppling username to the vault cmd it ran successfully. Now just gotta figure out why the username wasn't passed

**Comment by slamotte** [comment]
Sounds good, thanks for the update!
