### ISSUE TITLE
Only the most recent 1000 commits are fetched from Vault

### ISSUE THREAD

**Issue by koverly** [slamotte/vault2git#13]
When tested on an older Vault repo with 5000+ commits I discovered that only the last 1000 are fetched by the script.

The Vault client limits the version history to the last 1000 versions by default.  The entire history can be obtained by passing the argument `-rowlimit 0` to Vault along with the `versionhistory` command to override the default behavior.

```diff
diff --git a/converter.rb b/converter.rb
index 54af965..db6baaa 100644
--- a/converter.rb
+++ b/converter.rb
@@ -124,7 +124,7 @@ class Converter
                vault_command 'setworkingfolder', quote_value($options.source), $options.dest, false

                info "Fetch version history"
-               versions = vault_command('versionhistory') % :history
+               versions = vault_command('versionhistory', ["-rowlimit 0"]) % :history
                versions = versions.children.map do |item|
                  hash = {}
                  item.attributes.each do |attr|
```

**Comment by slamotte** [comment]
Very interesting! Care to make a pull request or shall I make the change?

**Comment by slamotte** [comment]
Thanks for the update!

**Comment by koverly** [comment]
Glad I could contribute.  Thanks for originating the script.  It has made migrating away from vault significantly easier.
