### ISSUE TITLE
converter.rb:62:in `co nvert': wrong number of arguments (0 for 2) (ArgumentError)

### ISSUE THREAD

**Issue by rajasekaran07** [slamotte/vault2git#16]
I cant run this application. I got the below error. Please help me to fix this issue.

C:\Users\URADHR1\Downloads\vault2git-master>ruby vault2git.rb --host localhost -
-repo "My Repo" C:\Project_repo\Edge-BK C:\Project_repo\Edge-Git
C:/Ruby193/lib/ruby/gems/1.9.1/gems/Converter-1.1.3.0/lib/converter.rb:62:in `co
nvert': wrong number of arguments (0 for 2) (ArgumentError)
        from vault2git.rb:5:in `<main>'

C:\Users\URADHR1\Downloads\vault2git-master>ruby -v
ruby 1.9.3p551 (2014-11-13) [i386-mingw32]

C:\Users\URADHR1\Downloads\vault2git-master>gem --version
1.8.29

ruby vault2git.rb --host localhost --repo "My Repo" C:\Project_repo\Test-BK C:\Project_repo\Test-Git

Kindly let me know what else I need to configure.

Regards,
Raja

**Comment by koverly-aps** [comment]
As the README indicates the slashes in the path must be a forward slash "/", not a backward slash "\" like you've shown.  You should also wrap the other arguments in quotes as well.

Try this instead:
`ruby vault2git.rb --host localhost --repo "My Repo" "C:/Project_repo/Test-BK" "C:/Project_repo/Test-Git"`

**Comment by slamotte** [comment]
Thanks @koverly-aps for pointing this out. I've been away and not checking email, apologies to @rajasekaran07 for not responding!
