### ISSUE TITLE
Fetch Version History Error: undefined method `children' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by medewarbux** [slamotte/vault2git#19]
### Problem
I cannot use old versions of ruby, so I hope that isn't the issue. 
**I tried checking for nil and initializing an array**, but it still errored out. 
Can you help? 

### Command
`C:\workspaces\vault2git-master>ruby vault2git.rb --host "azprd1vault1.healthds.com" --repo "Arrow" -u "ehansen" -p "password"  $/arrow C:/workspaces/arrow`

### Results in Error
 INFO vault2git: Starting at 2020-09-25 17:32:55 -0500
 INFO vault2git: Prepare destination folder
 INFO vault2git: Set Vault working folder
 INFO vault2git: Fetch version history
**nil
`Traceback (most recent call last):
        1: from vault2git.rb:6:in '<main>'
C:/workspaces/vault2git-master/converter.rb:132:in 'convert': undefined method 'children' for nil:NilClass (NoMethodError)`**

### Under **vault2git.rb**, I had to prefix **options** and **converter** or it ended in errors
`require 'rubygems' `
`require 'bundler'`
**`require 'C:\\workspaces\\vault2git-master  \\options'`**
**`require 'C:\\workspaces\\vault2git-master  \\converter'`**
Had to use absolute paths for the last 2

### In QUICKSTART.textile
gem install nokogiri -v 1.5.11 fails
I noticed that you updated it to 1.10.8 in an issue fix.
Once I installed that version, it succeeds. The file needs to be updated

### Also in that file:
 your example shows the c:\source\git\Alpha with the backslashes but in the README you specifically say it needs to be forward slashes even on windows. 
Can you correct this file?

### Environment:
Windows 10 - details at bottom
Running ruby 2.6.6p146 (2020-03-31 revision 67876) [x64-mingw32] 
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.17763 Build 17763
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	WA713260-VLCL02
System Manufacturer	VMware, Inc.
System Model	VMware7,1
System Type	x64-based PC
System SKU	
Processor	Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz, 2304 Mhz, 6 Core(s), 6 Logical Processor(s)
BIOS Version/Date	VMware, Inc. VMW71.00V.16221537.B64.2005150253, 5/15/2020
SMBIOS Version	2.7
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	Intel Corporation
BaseBoard Product	440BX Desktop Reference Platform
BaseBoard Version	None
Platform Role	Mobile
Secure Boot State	On
PCR7 Configuration	Binding Not Possible
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume2
Locale	United States
Hardware Abstraction Layer	Version = "10.0.17763.1432"
Time Zone	Central Daylight Time
Installed Physical Memory (RAM)	10.0 GB
Total Physical Memory	10.0 GB
Available Physical Memory	3.43 GB
Total Virtual Memory	13.0 GB
Available Virtual Memory	4.55 GB
Page File Space	3.00 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Not enabled
A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by slamotte** [comment]
Hi,

I pushed a few commits, most notably to use bundler correctly. I updated the docs to specify `bundle exec ruby vault2git ...` so hopefully now it will pick everything up. I hope it works. As mentioned in the readme, I no longer have access to a Windows machine or Vault to maintain this properly 🤞
