### ISSUE TITLE
Changes required for ruby 1.9 support

### ISSUE THREAD

**Issue by ErikNoren** [slamotte/vault2git#5]
I'm not a ruby user so I downloaded the ruby-installer recommended branch (1.9.3) as the readme document said it should work. It didn't. I figured out to change the require to require_relative on the converter.rb line but then it complained about assigning a variable and I gave up. Uninstalled, installed 1.8.7 and I was at least able to get to the vault2git usage message now (after doing a gem install bundler).

**Comment by koverly** [comment]
I would agree the requirements section should be updated to reflect that it only works with ruby 1.8.x.  I went through the same process as Erik of installing 1.9.3 and then reverting to 1.8.7.

**Comment by slamotte** [comment]
I'm confused. The requirements section does state that it needs Ruby 1.8.7. Am I missing something or are you? The 1.8.7 comment has been in place since April 7, 2011.

**Comment by koverly** [comment]
Sorry for not being more clear.  The requirements section states "Ruby 1.8.7 (should also work with 1.9.X)".  The "should also work with 1.9.X" led both Erik and I to start with 1.9.3 only to find that it doesn't work.  It would have saved us some time if 1.9.X was not referenced as we would have started with 1.8.7 instead.
