### ISSUE TITLE
Error at Fetch Version History

### ISSUE THREAD

**Issue by CommandLineDesign** [slamotte/vault2git#8]
I think this might be user error. I'm using Ruby 1.8.7:

F:\Development\FORT_Vault2Git\FORT_Applications\vault2git>vault2git.rb --host 20
8.76.28.136 --repo "wsn repository" $\800winev2 F:\Development\FORT_Vault2Git\Fo
rt_Root_git\oms
 INFO vault2git: Starting at Thu Jan 01 03:30:46 -0800 2015
 INFO vault2git: Prepare destination folder
 INFO vault2git: Set Vault working folder
 INFO vault2git: Fetch version history
./converter.rb:128:in `convert': undefined method `children' for nil:NilClass (N
oMethodError)
        from F:/Development/FORT_Vault2Git/FORT_Applications/vault2git/vault2git
.rb:7

F:\Development\FORT_Vault2Git\FORT_Applications\vault2git>

I am pretty sure there's something wrong with my execution, but I was hoping to get pointed in the right direction. It doesn't seem to matter what I invoke with. I get the Fetch Version History Convert error almost every time. Any idea what I'm doing wrong?

**Comment by rdstevens** [comment]
You probably need to pass in username and password credientials.

use: --user username --password password on the commandline
